project:
  type: website
  output-dir: docs

website:
  title: "Academic Portfolio"
  favicon: images/ColgateC.png
  sidebar:
    logo: images/ColgateSeal.png
    style: "docked"
    collapse-level: 1
    search: false
    contents:
      - href: index.qmd
        text: " Home"
        icon: house
      - href: about.qmd
        text: " About"
        icon: person
    # Math 240
      - section: "Computational Statistics"
        contents:
        - text: "Lab 2: Objects in R"
          href: Math240/Lab2/Lab2.qmd
        - text: "Lab 3: Objects in R 2"
          href: Math240/Lab3/Lab3.qmd
        - text: "Lab 5: Data Wrangling"
          href: Math240/Lab5/Lab5.qmd
        - text: "Lab 6: Graphs in R"
          href: Math240/Lab6/Lab6.qmd
        - text: "Lab 7: Data Distributions"
          href: Math240/Lab7/Lab7.qmd
        - text: "Lab 10: Point Estimation"
          href: Math240/Lab10/Lab10.qmd
        - text: "Lab 11: t-based Inference"
          href: Math240/Lab11/Lab11.qmd
      #MATH354
        #- section: "Data Analysis I"
        #  contents:


  page-footer: 
    left: "© 2026 Colgate University Student Portfolio"
    right: "[GitHub Source](https://github.com/rsernick)"
format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true



