project:
  type: website
  output-dir: docs

website:
  title: "Academic Portfolio"
  sidebar:
    logo: images/ColgateSeal.jpg
    style: "docked"
    collapse-level: 1
    search: false
    contents:
      - href: index.qmd
        text: " Home"
        icon: house
      - href: about.qmd
        text: " About"
        icon: person
    # Math 240
      - section: "Computational Statistics"
        contents:
        - text: "Lab 1"
  page-footer: 
    left: "© 2026 Colgate University Student Portfolio"
    right: "[GitHub Source](https://github.com/rsernick)"
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



